version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:SONARCLOUD_TOKEN
    HOST: prod/sonar:HOST
    Organization: prod/sonar:NCS Sample Project
    Project: prod/sonar:NCS Sonar Cloud
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - npm install
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/  
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
