version: 0.2


phases:
  install:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-cli-4.7.0.2747-linux/bin/
  build:
    commands:
      - sonar-scanner
