version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "sqp_6cc25ab2e332f0f5db98eb3a1d6d4a54151d2398"

phases:
  install:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-cli-4.7.0.2747-linux/bin/
  build:
    commands:
      - sonar-scanner
